### ISSUE TITLE
Allow for dynamic filtering at runtime 

### ISSUE THREAD

**Issue by jasnonaz** [dbt-labs/dbt_metrics#13]
Right now the metrics package does a great job of, when given a metric, time_grain, dimensions and calculations, returning an aggregation based off of that metric. In order to allow for maximum flexibility in how people are able to use and access these metrics, we should introduce an optional `filters` argument that would allow the user to apply sql-style filtering.

The benefit of this it is gives a huge range of flexibility into the information you can get out of a single metric, while maintaining consistency and avoiding having to make hundreds of metrics that are just different versions of filters people might need to apply. I think we'd be able to ensure accuracy here by making sure that any filtered columns where dimensions in the metric - if you can use a dimension in a metrics query you can filter on it and vice versa.

This syntax would allow you to filter a metric off of a single dimension, multiple dimensions and using LIKE operators. Imagine a hypothetical scenario where a user wanted to explore number of account sign ups by country and marketing campaign.

**Examples:**

_No filters:_

This would simply return the number of accounts by day.

`{{metrics.get_metric_sql(number_of_accounts, day, [], )}}`

_One filter:_

This would return the number of accounts by day only for accounts that signed up in the US.

`{{metrics.get_metric_sql(number_of_accounts, day, [],where=[country='United States"] )}}`

_Two filters:_

This would return the number of accounts by day from the United States where the marketing campaign had been attributed to Google.

`{{metrics.get_metric_sql(number_of_accounts, day, [],where=[country='United States",marketing_campaign='Google"] )}}`

_Two filters using substring matching:_

This would return the number of accounts by day from the United states where the campaign name matched any substring of "google_brand".

`{{metrics.get_metric_sql(number_of_accounts, day, [],where=[country='United States",marketing_campaign_name='google_brand%"] )}}`

As we begin creating the ability to serve more complex / dynamic use case it will be important for the metrics package to be able to create these dynamic, on the fly numbers with as little extraneous SQL code written by the end user as possible.

[Google sheet with examples: ](https://docs.google.com/spreadsheets/d/1bokie9ZJqqMAYQyqJbLxkPke7KHo2tMdTJ7DnTRdBb8/edit#gid=0)

**Comment by callum-mcdata** [comment]
I think this is an exceptionally good point and definitely something that we should add. The more I think about it, this field/parameter will also be extremely important from a BI integration standpoint. Right now, any integrating BI tool that wants to apply filters from their side of `dbt-server` will need to add filters down at the bottom of the macro query. 

While query planners are smart as heck, I have to imagine that this slows down the performance of the query because we're not applying the filter until the end of the query. It would be much faster to instead filter as early as possible, which is only do-able if its contained within the `get_metric_sql` macro itself.

Here's a question I have:
- Do we allow arbitrary filtering on **any** field within the base model OR do we restrict it to fields identified in the dimension list?
  - I worry that if we give users carte blanche to filter on non-dimension list fields then we offer too much flexibility. The user would be able to create filters that might return datasets non-standard for the metric.
  - Is it even possible to do this with string parsing? If the user is inputing arbitrary filter statements, we'd have to parse through them to figure out the column name and then check if its in the dimension list. That seems like a doozy.

### Requirements
1. Add `filters`/`where` as an additional optional input to the `metric.sql` macro.
2. Add the provided `filters` to the `source_query` CTE in the `get_metric_sql` macro. These would come **after** the metric filters.
