### ISSUE TITLE
[Feature] Should dbt_metrics support null-safe joins? In other words, is null = null?

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt_metrics#164]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

As shown in some [slack threads](https://getdbt.slack.com/archives/C02CCBBBR1D/p1666946923205959) and some Github Issues, some customers are running into issues where they expect their NULL values to be correctly represented in the output. This is not currently supported in dbt_metrics because we don't use NULL-SAFE operators for joins. Should we support this as a config option or macro parameter? 

### Describe alternatives you've considered

The easy alternative to this is to just state that null values need to be overwritten for metric calculations. 

### Who will this benefit?

Anyone who has null values in their dimensions

### Are you interested in contributing this feature?

Maybe

**Comment by josepfranquetf** [comment]
Hi @callum-mcdata, I think it would make sense to support null-safe joins. A sensible case would be when you have a derived metric which is a division between two metrics. If you have only one dimension which has a nul value (not strange), the metric could not be calculated. I really think that being worried of nulls can create a big friction to the user.

**Comment by callum-mcdata** [comment]
Hey @josepfranquetf. Do you mind laying out an example with data for the use case that you mentioned above? I'm not sure I fully understand the implications on derived metrics. I've got some opinions in this area after testing of my own but want to make sure I hear from users before settling on a path.

**Comment by josepfranquetf** [comment]
Hey @callum-mcdata. Imagine that you are running a `metrics.calculate` macro with one dimension (_marketing_source_) and a derived metric (_cac_), which is calculated as _investment_/_number_of_customers_. Additionally, _marketing_source_ takes 3 different values: _Facebook_, _Google_ and _null_.
In this case, _cac_ would be _null_ when _marketing_source_ is _null_ because null-safe joins are not supported (Although, _investment_ and _number_of_customers_ have positive values when marketing_source is _null_).

**Comment by opalh** [comment]
Hey @callum-mcdata, I was struggling with this issue before managed to understand what was happening. From my point of view, since metrics are created to have multiple dimensions it is problematic that you lose rows if one of the dimensions is null and for me, it doesn't seem reasonable to replace all nulls in my columns to be able to use metrics with dimensions.
Also, it was quite confusing to understand where the difference is coming from since the null rows were there but they had zero in the metric.

**Comment by callum-mcdata** [comment]
No commitment that we'll be implementing this but I wanted to dig into the method that we would use to resolve this issue. 

### Using A IS [ NOT ] DISTINCT FROM B
All righty, let's do some digging here for all our supported adapters:
- **Snowflake**: [Documentation here](https://docs.snowflake.com/en/sql-reference/functions/is-distinct-from.html). An example of this can be found in this [StackOverflow](https://stackoverflow.com/questions/70295189/snowflake-join-does-not-return-null-values-condition-matching-records-from-2-tab).
- **Redshift**: Unable to find any documentation on a native function to accomplish this. 
- **BigQuery**: [Documentation here](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#is_distinct). 
- **Databricks**: [Documentation here](https://docs.databricks.com/sql/language-manual/functions/isdistinct.html). Looks like we can use
- **Postgres**: [Documentation here.](https://www.postgresql.org/docs/current/functions-comparison.html) 

I suspect that this is the best syntax to use that is consistent across all the supported adapters. We could potentially need to figure out an alternative solution for Redshift but that is fine.
