### ISSUE TITLE
[Feature] Support sub-day grains

### ISSUE THREAD

**Issue by rfdearborn** [dbt-labs/dbt_metrics#166]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently, `day` is the most frequent supported grain. Higher frequencies - `hour`, `minute`, and `second` - would be useful  (see benefits below).

### Describe alternatives you've considered

I did try hacking this with a custom calendar, but unsuccessfully.  Given a `dim_minutes` model and a `new_users` metric, this returns daily counts duplicated over each day’s hours:
```sql
SELECT * 
FROM {{ metrics.calculate(
  metric('new_users'),
  grain='hour'
) }}
```

The reason is that metrics’ generated SQL first aggregates by day:
```
from (


    select 
    
        cast(base_model.created_at as date) as metric_date_day, -- timestamp field
        calendar_table.date_hour as date_hour,
        
        calendar_table.date_day as window_filter_date,
        

        
            (id) as property_to_aggregate

    from dbt.robdearborn.dim_users base_model 
    left join dbt.robdearborn.dim_minutes calendar_table

    
        on cast(base_model.created_at as date) = calendar_table.date_day
    

    where 1=1
) as base_query
```

### Who will this benefit?

There are undoubtedly others, but a couple use cases come immediately to mind:
- **metric monitoring, alerting and debugging** - e.g., I want to set up a job to query onboarding conversion each minute and notify if there's degradation, then be able to debug exactly when an issue started to occur
- **metric optimization** - e.g., I want to understand onboarding volume and conversion across time of day in order to allocate support resources

### Are you interested in contributing this feature?

Sure! But recognize there's a *lot* of activity round here at the moment, so don't want to add coordination complexity.

**Comment by rijnhardtkotze** [comment]
The idea of this has me excited. Is this actively being prioritised in the roadmap?

**Comment by callum-mcdata** [comment]
Hi folks! Our semantic layer team is currently focused on something else for the coming weeks (🤫 more information coming soon!) so this is definitely open if either of you want to take it on! I will caution anyone interested, I think this is probably a good chunk of work because the base level of `day` is built into the base macros. 

I'd recommend starting to look at:
- `gen_aggregate_cte`: This is the cte that performs the aggregation of the base dataset. Right now it operates under the assumption that the data from the base query exists at the day grain so there are probably a lot of changes you'd need to make here.
- `gen_base_query`: This is the base subquery selecting the data from the model and then joining to the calendar to have the day grain information. 
- `dbt_metrics_default_calendar` : This is the default calendar included in the metrics package. You'd want to figure out a way to break this down to the lower components, which could be a **lot** of rows 😅 

If you have any questions, please drop them here or in a draft PR and happy to collaborate there. Otherwise if neither of you are interested, I can surface it around to the dbt-labs team and we can start to think about it in our longer term roadmap.

**Comment by smarthg** [comment]
Hello @callum-mcdata, as suggested by you I have proposed some changes to support hourly grain in dbt metrics. This approach keeps the base grain to be `day` for `day, week, month ..` grains but dynamically uses `hour` base grain when an `hourly` grain is passed. This will dynamically spline the calendar CTE to create a `day_hour` column and update the join logic.

TODO: 
1.  Add support for windowing by sub day grain. 
2. Add tests

Still new to the package and this is my first contribution so would love to get some more pointers if possible on the Draft PR #219.

I was able to manually test the hourly grain for snowflake but with no secondary calculations or windowing.
