### ISSUE TITLE
[SEMANTIC-66] [Feature] Add median to dbt_metrics

### ISSUE THREAD

**Issue by etobey-brightline** [dbt-labs/dbt_metrics#180]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Add median as a calculation_method in dbt metrics. 

### Describe alternatives you've considered

Override current macro with my own code.

### Who will this benefit?

This will benefit all analytics engineers as median is sometimes a better descriptive statistic than average when outliers exist.

**Comment by callum-mcdata** [comment]
Let's do a little research on this one. Given our supported adapters for this package, is median provided in each one and does it operate the same way?

- **Postgres**: 🟨  Looks like postgres doesn't have a native median function. [Stack Overflow here shows how to get around this.](https://stackoverflow.com/questions/12067656/how-do-i-get-min-median-and-max-from-my-query-in-postgresql)
- **Redshift**: ✅  [Documentation here](https://docs.aws.amazon.com/redshift/latest/dg/r_MEDIAN.html)
- **Snowflake**: ✅  [Documentation here](https://docs.snowflake.com/en/sql-reference/functions/median.html)
- **BigQuery**: 🟨   Looks like bigquery doesn't have a native median function. [Our wonderful friends over at count](https://count.co/sql-resources/bigquery-standard-sql/median) show an example of how to do so using Percentile_cont though.
- **Databricks**: ✅  [Documentation here](https://docs.databricks.com/sql/language-manual/functions/median.html)

The biggest issue here is that both of the proposed solutions in the BigQuery and Postgres posts recommend using window functions in order to calculate the median. This is a bit of an issue for us based on how we handle aggregation. We use `group by` in the `gen_aggregation_cte`, which means we'd need to rewrite portions of how we handle that. 

I need to give this some more thought 🤔

**Comment by PaxonF** [comment]
> The biggest issue here is that both of the proposed solutions in the BigQuery and Postgres posts recommend using window functions in order to calculate the median. This is a bit of an issue for us based on how we handle aggregation. We use `group by` in the `gen_aggregation_cte`, which means we'd need to rewrite portions of how we handle that.
> 
> I need to give this some more thought 🤔

@callum-mcdata 

Unsure if this is an appropriate option, but BigQuery does provide [approximate aggregation](https://cloud.google.com/bigquery/docs/reference/standard-sql/approximate_aggregate_functions) (group by) functions that are somewhat equivalent to their window function counterparts. Maybe it's a lot of overhead to convert dbt metrics to be able to use window functions, but this might provide some partial functionality in the short term.

**Comment by callum-mcdata** [comment]
@PaxonF that was incredibly helpful! 

After some more testing I was able to resolve the issue for Postgres - it supports running `percentile_cont` as an aggregate function within a specific group. The bigger issue is BigQuery, which doesn't support that behavior.

The way I see it, I think there are two options forward:
1. Rewrite large portions of dbt_metrics to allow for window functions in the base aggregation.
2. Use approximate aggregates, such as the following example `NTH(51, QUANTILES(x,101))`

The issue with option 2 is that there is no guarantee that the answer is correct - it is an approximate. Reluctantly I think option 1 is the best path forward.

**Comment by callum-mcdata** [comment]
There is an alternative route forward!

### The Problem

The widely accepted community workaround to calculate `median` in BQ is to use window functions. Unfortunately for us, that doesn’t work with the way that we are currently constructing the SQL. Let’s walk through why.

In today’s metrics package, [we first construct](https://github.com/dbt-labs/dbt_metrics/blob/main/macros/sql_gen/gen_base_query.sql) the `base_query` that selects from the underlying model. Here is an example of this code:

```sql
select 
	cast(base_model.order_date as date) as metric_date_day, -- timestamp field
	calendar_table.date_month as date_month,
	calendar_table.date_day as window_filter_date,
	base_model.had_discount,
	(discount_total) as property_to_aggregate
from model_name base_model 
left join ... calendar_table
	on cast(base_model.order_date as date) = calendar_table.date_day
where 1=1
```

This code does not apply any aggregations because that is handled in the `aggregation_cte` for which the base query is the source. See below:

```sql
select
	date_month,
  had_discount,
  avg(property_to_aggregate) as base_average_metric,
  logical_or(metric_date_day is not null) as has_data
from (above query)
where 1=1
group by 1, 2
```

This works great when we only need to run aggregation queries but once we begin to think about aggregations or metrics that require window functions, we run into more problems. Namely, window functions and group by’s don’t get along.

### The future

What would a query that supports window functions look like? Well the first step would be moving the window calculation into the base query - this allows us to calculate the correct value for each of the individual aggregation groups. 

```sql
select 
	calendar_table.date_month as date_month,
	base_model.dimension,

	## Some macro to properly render the function. Lets walk through median in BQ
	percentile_cont(metric_value, 0.5) over (
			partition by date_month, dimension
	) as property_to_aggregate

from ... base_model 
left join ... calendar_table
	on cast(base_model.order_date as date) = calendar_table.date_day
where 1=1
```

The window function duplicates this value across all of the rows contained within this group but it gets reduced down in the following query.

```sql
select
	date_month,
  dimension,
  any_value(property_to_aggregate) as base_median_metric,
	-- average as well
	-- adapter macro for any_value.
  logical_or(metric_date_day is not null) as has_data
from (above query)
where 1=1
group by 1, 2
```

****************************************Why does this work:**************************************** This works because the window function creates the correct value for the aggregation among ********************************************************************************all of the rows aggregated.******************************************************************************** So in the first query, every single row for January with dimension value X would have the same value in the `property_to_aggregate` column. So when we aggregate down to a single row, we can select any value with confidence that they are correct. 

This gets us a resulting dataset that is at the correct grain and has the correct values for each of those grains. 

********PROS********

- This opens up a host of other functions that we wouldn’t have previously been able to do. For example, latest value. This function exists in Snowflake but the way to calculate it in postgres is done through window functions. With this framework we can use this.
- This allows us to keep the same framework that we have with only a few changes.

**CONS**

- There is potential for high compute costs because we’re applying the window function on the base dataset and so it is being calculated at the lowest grain. This is acceptable though - to [share a quote](https://wiki.c2.com/?MakeItWorkMakeItRightMakeItFast) the lovely and intelligent @dbeatty10 - "Make it work, make it right, make it fast". This is the first step.

### Work to be done

So what needs to change in the metrics package today?

- Changes to `generate_primary_metric_aggregate`
    - Support selecting `any_value` for any implementation that needs it. Means that we’ll need a mapping inside this macro for any calculation_method/adapter combo that needs any value
- Changes to `gen_base_query`
    - Creation of a new macro called `gen_base_query_metric_value`
    - This macro would contain the current metric logic ********and******** an understanding of when to use the window function

**Comment by callum-mcdata** [comment]
Hi folks! This work was completed as part of #208 and will be released with the `1.4.0` release later this month. Thanks for the suggestion!

**Comment by PaxonF** [comment]
Amazing @callum-mcdata! Excited to try it out.

Perhaps this is worth a separate ticket entirely, but does this recent PR open the door to doing aggregations such as percentiles (i.e. 90th, 95th, 99th percentile), standard deviation, variance, and other [statistical functions](https://cloud.google.com/bigquery/docs/reference/standard-sql/statistical_aggregate_functions) in the future?

**Comment by callum-mcdata** [comment]
@PaxonF Yep - this sets up a framework of being able to pass the aggregation down to the base query with a window function and then aggregate with `any_value`. We'll probably want to do some performance testing at scale for these kinds of functions though - this is definitely in the `Make it work` step of the process.
