### ISSUE TITLE
Period Over Period Cast To Float

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt_metrics#62]
## Description
Once again, the most confusing and asinine aspect of PostgreSQL strikes again - if you do simple division, it returns as an integer instead of a float or floating numeric.

### Example:
![image](https://user-images.githubusercontent.com/101437052/180315005-e040bd07-fb13-45f4-8c81-9d57f2f549e8.png)

### Solution
In the `period_over_period` secondary calculation, we need to cast to float for Postgres and Redshift as they both exhibit this known behavior.

**Comment by callum-mcdata** [comment]
Resolution was moving the `cast( as float)` to the numerator instead of the full division in `default__metric_comparison_strategy_ratio`.

```
cast(coalesce({{ metric_name }}, 0) as {{ dbt_utils.type_float() }}) / nullif({{ calc_sql }}, 0) 
```

Will go out with next PR.

**Comment by dbeatty10** [comment]
Starting with Core 1.2, you can use [`type_float`](https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros#type_float) from the global namespace:
```sql
cast(coalesce({{ metric_name }}, 0) as {{ type_float() }}) / nullif({{ calc_sql }}, 0) 
```

An alternative is giving it an explicit namespace:
```sql
cast(coalesce({{ metric_name }}, 0) as {{ dbt.type_float() }}) / nullif({{ calc_sql }}, 0) 
```

I prefer the former.

I'd recommend making the change sooner rather than later, because the 1.0 release of dbt_utils intends to drop `type_float` altogether.

Side note: not currently on the roadmap, but I'm attracted to dbt Core containing cross-database casting macros like `cast_as_float` and `safe_cast_as_float`.
